# Light state control
- alias: mqtt_light_state
  trigger:
  - platform: mqtt
    topic: 'home/light/+/state/set'
  action: 
  - service: script.mqtt_light_state
    data: 
      topic: "{{ trigger.topic }}"
      payload: "{{ trigger.payload }}"

# Light brightness control
- alias: mqtt_light_brightness
  trigger:
  - platform: mqtt
    topic: 'home/light/+/brightness/set'
  action:
  - service: script.mqtt_light_brightness
    data:
      topic: "{{ trigger.topic }}"
      payload: "{{ trigger.payload }}"

# Light colour temperature control
- alias: mqtt_light_ct
  trigger:
  - platform: mqtt
    topic: 'home/light/+/color_temp/set'
  action:
  - service: script.mqtt_light_ct
    data:
      topic: "{{ trigger.topic }}"
      payload: "{{ trigger.payload }}"

# Switch state control
- alias: mqtt_switch_state
  trigger:
  - platform: mqtt
    topic: 'home/switch/+/state/set'
  action:
  - service: script.mqtt_switch_state
    data:
      topic: "{{ trigger.topic }}"
      payload: "{{ trigger.payload }}"

# Cover position control
- alias: mqtt_cover_position
  trigger:
  - platform: mqtt
    topic: 'home/cover/+/current_position/set'
  action:
  - service: script.mqtt_cover_position
    data:
      topic: "{{ trigger.topic }}"
      payload: "{{ trigger.payload }}"